### ISSUE TITLE
Create Edit component

### ISSUE THREAD

**Issue by VernitaJ** [marcopeg-dev/m07-cv-frontend#10]
Add the editing component, and add it to the existing edit-view component.

**Comment by Deve1980** [comment]
Remove undefined id from users array 

![undefiend-id](https://user-images.githubusercontent.com/61511520/75546411-c182fc00-5a28-11ea-8200-c55997dca880.png)

**Comment by NicolaWinterson** [comment]
> Remove undefined id from users array
> 
> ![undefiend-id](https://user-images.githubusercontent.com/61511520/75546411-c182fc00-5a28-11ea-8200-c55997dca880.png)

Hi, from looking at the code, I think that we will have to remove/not display blank users at a different point e.g. HomeView component, rather than the EditView component
