### ISSUE TITLE
Add a loading screen while Heroku wakes up

### ISSUE THREAD

**Issue by marcopeg** [marcopeg-dev/m07-cv-frontend#11]
Right now we deploy our backend on Heroku for free. The consequence is that after 30 minutes of inactivity, the backend goes to sleep.

The next request takes a few seconds to warm up the backen (well, up to 10s!) and it would cause a bad user experience into the main UI.

We should add a loading screen with some form of nice animation that covers the entire app, makes a first request to the backend (mabe toward a `/status` route that just returns `+ok`) and then goes away.

**Comment by VernitaJ** [comment]
Could I edit the current 'LoadingIndicator' component for this purpose?

**Comment by marcopeg** [comment]
@VernitaJ I believe it is best to create a new component for that, it will also need another custom hook as state.
