### ISSUE TITLE
Create Search bar

### ISSUE THREAD

**Issue by VernitaJ** [marcopeg-dev/m07-cv-frontend#18]
Create a component to filter through users and show searched

**Comment by Btolara** [comment]
Create this beautiful and useful design to the search bar in Home view (New Component)

![Screen Shot 2020-02-23 at 13 36 55](https://user-images.githubusercontent.com/55560917/75112181-9754c700-5641-11ea-8e5a-8b7d637026c0.png)

**Comment by farooq029** [comment]
Is it  Final or needed more changes?


![Search bar](https://user-images.githubusercontent.com/34084867/75638918-923ddc00-5c2e-11ea-821d-d34a85e3ed6d.png)

**Comment by Btolara** [comment]
@farooq029 we are still working on that

**Comment by paulatorre** [comment]
Sorry @farooq029 never saw this message.

@Btolara I think now the code is ready to apply the styling

**Comment by farooq029** [comment]
Search bar pull request merged but it's not showing in the master branch

**Comment by farooq029** [comment]
It's looking like this in search bar branch 


![Screenshot 2020-03-05 at 10 28 06](https://user-images.githubusercontent.com/34084867/75967498-35f7e800-5ecc-11ea-9e88-b882f6e345b5.png)
