### ISSUE TITLE
Profile picture to show on profile view

### ISSUE THREAD

**Issue by VernitaJ** [marcopeg-dev/m07-cv-frontend#30]
For better UI

**Comment by Btolara** [comment]
Hi @VernitaJ do you think this one is good for the profile?
![Screen Shot 2020-02-28 at 19 11 28](https://user-images.githubusercontent.com/55560917/75574110-5c49fd80-5a5e-11ea-848a-7014e6d6fb98.png)

**Comment by VernitaJ** [comment]
Yeah, I like this a lot. It'll look great; and also gives us an idea on
what else we can add. Well done

**Comment by farooq029** [comment]
@Btolara Have you started work on this?

**Comment by VernitaJ** [comment]
@farooq029 I've created a PR. Please go review and approve if correct.
