### ISSUE TITLE
CSS fix to EditView component

### ISSUE THREAD

**Issue by NicolaWinterson** [marcopeg-dev/m07-cv-frontend#32]

**Comment by NicolaWinterson** [comment]
I have already made and committed changes to the CSS of EditView component. I am just waiting for permission to push to the repo!

**Comment by VernitaJ** [comment]
Can you create a pull request that is related to this issue? Create branch feature/32' and create pull request.

**Comment by NicolaWinterson** [comment]
> Can you create a pull request that is related to this issue? Create branch feature/32' and create pull request.

Hi, I can't make pull requests (please see: https://foocoding-newcomers.slack.com/archives/CNHP8FVEH/p1582963656013900)
